twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/Default': Default
        '%kernel.project_dir%/templates/Emails': Emails

when@test:
    twig:
        strict_variables: true